const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('tv', {
  getApps: () => ipcRenderer.invoke('apps:get'),
  listFiles: (directoryPath) => ipcRenderer.invoke('files:list', directoryPath),
  openFile: (filePath) => ipcRenderer.invoke('files:open', filePath),
  addApp: (app) => ipcRenderer.invoke('apps:add', app),
  getSystemApps: () => ipcRenderer.invoke('system-apps:get'),
  addSystemApp: (desktopId) => ipcRenderer.invoke('system-apps:add', desktopId),
  getBackground: () => ipcRenderer.invoke('background:get'),
  chooseBackground: () => ipcRenderer.invoke('background:choose'),
  clearBackground: () => ipcRenderer.invoke('background:clear'),
  deleteApp: (id) => ipcRenderer.invoke('apps:delete', id),
  openApp: (app) => ipcRenderer.invoke('app:open', app),
  browserBack: () => ipcRenderer.invoke('browser:back'),
  goHome: () => ipcRenderer.invoke('browser:home'),
  refresh: () => ipcRenderer.invoke('browser:refresh'),
  focusBrowser: () => ipcRenderer.invoke('browser:focus'),
  toggleBrowserFullscreen: () => ipcRenderer.invoke('browser:fullscreen'),
  mediaAction: (action) => ipcRenderer.invoke('media:action', action),
  setBrowserKeyboard: (visible) => ipcRenderer.invoke('browser:keyboard', visible),
  keyboardInput: (input) => ipcRenderer.invoke('keyboard:input', input),
  getPreferences: () => ipcRenderer.invoke('settings:get-preferences'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setVolume: (volume) => ipcRenderer.invoke('audio:set-volume', volume),
  toggleMute: () => ipcRenderer.invoke('audio:toggle-mute'),
  selectAudioOutput: (id) => ipcRenderer.invoke('audio:select-output', id),
  getDisplays: () => ipcRenderer.invoke('display:get'),
  applyDisplay: (settings) => ipcRenderer.invoke('display:apply', settings),
  setPowerSettings: (settings) => ipcRenderer.invoke('power:set', settings),
  scanWifi: () => ipcRenderer.invoke('wifi:scan'),
  toggleWifi: (enabled) => ipcRenderer.invoke('wifi:toggle', enabled),
  connectWifi: (candidate) => ipcRenderer.invoke('wifi:connect', candidate),
  getBluetooth: () => ipcRenderer.invoke('bluetooth:get'),
  scanBluetooth: () => ipcRenderer.invoke('bluetooth:scan'),
  toggleBluetooth: (enabled) => ipcRenderer.invoke('bluetooth:toggle', enabled),
  toggleBluetoothDevice: (address) => ipcRenderer.invoke('bluetooth:device-toggle', address),
  setLanguage: (language) => ipcRenderer.invoke('language:set', language),
  systemAction: (action) => ipcRenderer.invoke('system:action', action),
  toggleFullscreen: () => ipcRenderer.invoke('window:toggle-fullscreen'),
  setConfirmationVisible: (visible) => ipcRenderer.invoke('window:confirmation-visible', visible),
  getAppInfo: () => ipcRenderer.invoke('app:get-info'),
  getUpdateState: () => ipcRenderer.invoke('update:get-state'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onBrowserState: (callback) => ipcRenderer.on('browser:state', (_, state) => callback(state)),
  onBrowserToolbarRequested: (callback) => ipcRenderer.on('browser:toolbar', callback),
  onHomeRequested: (callback) => ipcRenderer.on('launcher:home', callback),
  onSystemActionRequested: (callback) => ipcRenderer.on('launcher:system-action', (_, action) => callback(action)),
  onUpdateState: (callback) => ipcRenderer.on('update:state', (_, state) => callback(state))
});
