const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('tv', {
  getApps: () => ipcRenderer.invoke('apps:get'),
  listFiles: (directoryPath) => ipcRenderer.invoke('files:list', directoryPath),
  openFile: (filePath) => ipcRenderer.invoke('files:open', filePath),
  addApp: (app) => ipcRenderer.invoke('apps:add', app),
  getSystemApps: () => ipcRenderer.invoke('system-apps:get'),
  addSystemApp: (desktopId) => ipcRenderer.invoke('system-apps:add', desktopId),
  listFlatpaks: () => ipcRenderer.invoke('flatpak:list'),
  searchFlatpaks: (query) => ipcRenderer.invoke('flatpak:search', query),
  installFlatpak: (appId) => ipcRenderer.invoke('flatpak:install', appId),
  uninstallFlatpak: (appId) => ipcRenderer.invoke('flatpak:uninstall', appId),
  updateFlatpaks: () => ipcRenderer.invoke('flatpak:update'),
  getBackground: () => ipcRenderer.invoke('background:get'),
  chooseBackground: () => ipcRenderer.invoke('background:choose'),
  clearBackground: () => ipcRenderer.invoke('background:clear'),
  deleteApp: (id) => ipcRenderer.invoke('apps:delete', id),
  setFavorite: (id, favorite) => ipcRenderer.invoke('apps:favorite', id, favorite),
  moveApp: (id, direction) => ipcRenderer.invoke('apps:move', id, direction),
  setKidsAllowed: (id, allowed) => ipcRenderer.invoke('apps:set-kids', id, allowed),
  getProfile: () => ipcRenderer.invoke('profile:get'),
  setProfile: (profile, pin) => ipcRenderer.invoke('profile:set', profile, pin),
  setParentalPin: (candidate) => ipcRenderer.invoke('parental:set-pin', candidate),
  openApp: (app) => ipcRenderer.invoke('app:open', app),
  getActiveApps: () => ipcRenderer.invoke('active-apps:get'),
  activateApp: (appId) => ipcRenderer.invoke('active-apps:activate', appId),
  closeActiveApp: (appId) => ipcRenderer.invoke('active-apps:close', appId),
  getContentSources: () => ipcRenderer.invoke('content:sources'),
  getMovieSuggestion: () => ipcRenderer.invoke('content:movie-suggestion'),
  openContent: (sourceId, type, language, movie = '') => ipcRenderer.invoke('content:open', sourceId, type, language, movie),
  openKinopoiskMovie: (kinopoiskId) => ipcRenderer.invoke('content:open-kinopoisk', kinopoiskId),
  browserBack: () => ipcRenderer.invoke('browser:back'),
  goHome: () => ipcRenderer.invoke('browser:home'),
  refresh: () => ipcRenderer.invoke('browser:refresh'),
  focusBrowser: () => ipcRenderer.invoke('browser:focus'),
  toggleBrowserFullscreen: () => ipcRenderer.invoke('browser:fullscreen'),
  mediaAction: (action) => ipcRenderer.invoke('media:action', action),
  setBrowserKeyboard: (visible) => ipcRenderer.invoke('browser:keyboard', visible),
  keyboardInput: (input) => ipcRenderer.invoke('keyboard:input', input),
  getPreferences: () => ipcRenderer.invoke('settings:get-preferences'),
  getWeather: (language, force = false) => ipcRenderer.invoke('weather:get', language, force),
  setWeatherCity: (city, language) => ipcRenderer.invoke('weather:set-city', city, language),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  completeOnboarding: () => ipcRenderer.invoke('onboarding:complete'),
  getDiagnostics: () => ipcRenderer.invoke('diagnostics:get'),
  exportDiagnostics: () => ipcRenderer.invoke('diagnostics:export'),
  setVolume: (volume) => ipcRenderer.invoke('audio:set-volume', volume),
  toggleMute: () => ipcRenderer.invoke('audio:toggle-mute'),
  selectAudioOutput: (id) => ipcRenderer.invoke('audio:select-output', id),
  getDisplays: () => ipcRenderer.invoke('display:get'),
  applyDisplay: (settings) => ipcRenderer.invoke('display:apply', settings),
  setPowerSettings: (settings) => ipcRenderer.invoke('power:set', settings),
  setAutologin: (enabled) => ipcRenderer.invoke('autologin:set', enabled),
  setCec: (enabled) => ipcRenderer.invoke('cec:set', enabled),
  setAutoHdmiAudio: (enabled) => ipcRenderer.invoke('hdmi-audio:set', enabled),
  scanWifi: () => ipcRenderer.invoke('wifi:scan'),
  toggleWifi: (enabled) => ipcRenderer.invoke('wifi:toggle', enabled),
  connectWifi: (candidate) => ipcRenderer.invoke('wifi:connect', candidate),
  getBluetooth: () => ipcRenderer.invoke('bluetooth:get'),
  scanBluetooth: () => ipcRenderer.invoke('bluetooth:scan'),
  toggleBluetooth: (enabled) => ipcRenderer.invoke('bluetooth:toggle', enabled),
  toggleBluetoothDevice: (address) => ipcRenderer.invoke('bluetooth:device-toggle', address),
  setLanguage: (language) => ipcRenderer.invoke('language:set', language),
  setScreensaverTimeout: (timeout) => ipcRenderer.invoke('appearance:set-screensaver', timeout),
  systemAction: (action) => ipcRenderer.invoke('system:action', action),
  toggleFullscreen: () => ipcRenderer.invoke('window:toggle-fullscreen'),
  setConfirmationVisible: (visible) => ipcRenderer.invoke('window:confirmation-visible', visible),
  getAppInfo: () => ipcRenderer.invoke('app:get-info'),
  getUpdateState: () => ipcRenderer.invoke('update:get-state'),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onBrowserState: (callback) => ipcRenderer.on('browser:state', (_, state) => callback(state)),
  onActiveAppsChanged: (callback) => ipcRenderer.on('active-apps:changed', (_, apps) => callback(apps)),
  onBrowserToolbarRequested: (callback) => ipcRenderer.on('browser:toolbar', callback),
  onHomeRequested: (callback) => ipcRenderer.on('launcher:home', callback),
  onSystemActionRequested: (callback) => ipcRenderer.on('launcher:system-action', (_, action) => callback(action)),
  onUpdateState: (callback) => ipcRenderer.on('update:state', (_, state) => callback(state)),
  onHardwareChanged: (callback) => ipcRenderer.on('system:hardware-changed', (_event, change) => callback(change))
});
